baseURL = "http://dutchdataworks.nl"
languageCode = "en-us"
title = "DUTCH DATAWORKS"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Job"


[params]
    greeting = "Job Visser"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:jobvisserhcm@gmail.com"

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/jobvisser/"

    # [[params.links]]
    #     icon = "github"
    #     title = "Github"
    #     url = "https://github.com/"


    [params.colors]
        background = "#81c6ff"
        foreground = "#edf7ff"
        hover = "#ffba82"